server:
  Port: :5555
  JwtSecretKey: secretkey

postgres:
  PostgresqlHost: localhost
  PostgresqlPort: 5432
  PostgresqlUser: postgres
  PostgresqlPassword: password
  PostgresqlDbname: postgres
  PostgresqlSslmode: false